/**
 * pdf-logic.js
 * Purpose: Generates a professional PDF report for livestock management.
 */

export const pdfService = {
    generateAnimalReport(animalData, aiDiagnosis) {
        const { jsPDF } = window.jspdf;
        const doc = new jsPDF();

        // 1. Header & Branding
        doc.setFontSize(22);
        doc.setTextColor(46, 204, 113); // Riwi Green
        doc.text("FINCAPP - Livestock Report", 20, 20);

        // 2. Animal Details
        doc.setFontSize(14);
        doc.setTextColor(0, 0, 0);
        doc.text(`Animal ID: ${animalData.id}`, 20, 40);
        doc.text(`Current Weight: ${animalData.weight} kg`, 20, 50);
        doc.text(`Date: ${new Date().toLocaleDateString()}`, 20, 60);

        // 3. AI Insights Section
        doc.setDrawColor(46, 204, 113);
        doc.line(20, 70, 190, 70); // Decorative line
        
        doc.setFont("helvetica", "bold");
        doc.text("AI Veterinary Diagnosis:", 20, 80);
        
        doc.setFont("helvetica", "normal");
        const splitDiagnosis = doc.splitTextToSize(aiDiagnosis, 170);
        doc.text(splitDiagnosis, 20, 90);

        // 4. Footer
        doc.setFontSize(10);
        doc.text("Generated by FincApp Intelligence System", 20, 280);

        // 5. Save the file
        doc.save(`Report_Animal_${animalData.id}.pdf`);
    }
};